### ISSUE TITLE
Contact groups do NOT show for selecting 

### ISSUE THREAD

**Issue by StanTody** [chenxiaolong/BCR#620] opened 2024-10-25 12:01 UTC
At first, I really appreciate the new feature for creating rules for auto recording calls - thank you very much for it !

But unfortunately on my phone I can NOT select a contact group for creating a rule - the select group dialogue appears empty (see attachments).

All my contacts are in local phone account (see attachments)
![Screenshot_20241025_150552_True Phone_1](https://github.com/user-attachments/assets/1113e1ab-35b6-48ba-a372-2f46117b3752)
![Screenshot_20241025_150532_True Phone_1](https://github.com/user-attachments/assets/c40721a7-5e36-41d2-9b48-07d273ba6d5d)
![Screenshot_20241025_150502_BCR](https://github.com/user-attachments/assets/4e92f753-7865-4dbf-9be6-66b8b8865636)
![Screenshot_20241025_150513_BCR](https://github.com/user-attachments/assets/8241cfbf-46a2-406b-924d-e83daa9cd84d)
.
Phone: Samsung S23
ROM: One UI 6.0

**Comment by chenxiaolong** [comment] 2024-10-25 14:47
Can you try installing a different contacts app, like Fossify Contacts, and seeing if the groups appear there? I just want to make sure the Samsung contacts app is actually storing the groups in the system database and not in its own database.

**Comment by chenxiaolong** [comment] 2024-10-25 17:15
Hmm, if that's the case, I'm not sure what the issue is. Please grab a logcat immediately immediately after opening BCR's empty contact group screen and upload that.

If you're familiar with adb, you can grab the logcat with `adb logcat -d > logcat.txt`. Otherwise, you can use a logcat app.

> Remind you that my contacts are in LOCAL phone account, not in Google account.

That doesn't make a difference. All groups, regardless of where they're stored are exposed to apps the same way.

**Comment by StanTody** [comment] 2024-10-25 20:42
> Please grab a logcat immediately immediately after opening BCR's empty contact group screen and upload that.

Here it is: 
[logcat.part.txt](https://github.com/user-attachments/files/17527409/logcat.part.txt)

**Comment by chenxiaolong** [comment] 2024-10-25 22:35
Hmm, it doesn't look like that was able to capture the logs.

Please try this test build: [BCR-1.72.r6.gef3b005-release.zip](https://github.com/user-attachments/files/17528053/BCR-1.72.r6.gef3b005-release.zip) There's no difference in functionality, but I added a new option to save the logs.

Try long pressing BCR's version number to enable debug mode, open the empty contact group screen, and then go back to BCR's main screen and hit the new save logs option.

**Comment by StanTody** [comment] 2024-10-26 06:44
> and hit the new save logs option

Hi again! Here is the saved log: 
[Logcat.20241026_1000.zip](https://github.com/user-attachments/files/17529316/Logcat.20241026_1000.zip)

**Comment by chenxiaolong** [comment] 2024-10-27 00:36
Thanks for the logs!

This should be fixed by #626. Please give this test build a try and upload new logs if you still run into issues: [BCR-1.72.r14.gf81cbfd-release.zip](https://github.com/user-attachments/files/17532405/BCR-1.72.r14.gf81cbfd-release.zip)

**Comment by StanTody** [comment] 2024-10-27 10:31
> Please give this test build a try and upload new logs

In this build groups are visible, BUT each group is shown TWICE (see attachments).

Here is the log:
[Logcat.20241027.zip](https://github.com/user-attachments/files/17533530/Logcat.20241027.zip)


![Screenshot_20241027_124523_BCR](https://github.com/user-attachments/assets/fe600afe-88da-4411-ba6e-e08276df26e2)

**Comment by chenxiaolong** [comment] 2024-10-27 20:46
Can you install this new test build and take another screenshot? (Feel free to black out the `accountName` parts). [BCR-1.72.r15.gb83f245-release.zip](https://github.com/user-attachments/files/17535393/BCR-1.72.r15.gb83f245-release.zip)

The screen should look something like this: [screenshot](https://github.com/user-attachments/assets/adf57d7f-a582-4216-b3c8-dbdcdf9cead2)

I want to see if these groups are actually duplicates (same rowId and sourceId) or if they are different groups with the same title.

**Comment by StanTody** [comment] 2024-10-28 07:21
> I want to see if these groups are actually duplicates

No, they obviously are different ones with same names. Maybe you can add account name to group name, so they can be  identified uniquely?
![Screenshot_20241028_085231_BCR_1](https://github.com/user-attachments/assets/1247c4f5-c463-43a7-8821-08f2c5f46e75)

**Comment by chenxiaolong** [comment] 2024-10-29 23:19
The account name has been added to the description of each group in #626, which will be included in BCR 1.73.

**Closed** 2024-10-29 23:18 UTC
Labels: bug

**Comment by StanTody** [comment] 2024-11-02 18:07
Thank you very much and I wish you everything best !
