### ISSUE TITLE
It will be better if this app can record calls from other apps such as Signal or Whatsapp. 

### ISSUE THREAD

**Issue by FattyMattier** [chenxiaolong/BCR#341] opened 2023-05-11 07:22 UTC

**Comment by chenxiaolong** [comment] 2023-05-11 15:47
Sorry, this is not something that will be implemented in BCR. BCR is heavily tied in with how cellular calls work on Android and cannot handle calls in third party apps. You'll have to use a different call recorder for that.

(Duplicate of #228, #235, #267, #340)

**Closed by chenxiaolong** 2023-05-11 15:47 UTC
