### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by metaathron** [chenxiaolong/BCR#246] opened 2023-02-15 19:18 UTC
After installation of BCR on rooted stock firmware, it causes bootloop. Phone waits until I unlock it and then reboots after approximately 2 seconds. I have tried it with only this magisk module installed. Same behaviour is observed when I try to use ACR Phone Helper module (after update to Android 13).
Phone: Xiaomi Redmi Note 11 Pro+ 5G EEA
MIUI: 14.0.2.0 (TKTEUXM)
Android: 13

**Comment by chenxiaolong** [comment] 2023-02-15 20:13
Hmm, this is the second issue someone has reported with MIUI 14 (1st was #242).

> Same behaviour is observed when I try to use ACR Phone Helper module (after update to Android 13).

That's good to know. I wonder if MIUI added some mechanism that breaks installation of new system apps.

Does it make a difference if right after installing the Magisk module and before rebooting, you extract the zip and also install `system/priv-app/com.chiller3.bcr/app-release.apk` directly?

(I assume you already know this, but just in case: Magisk modules can be disabled in safe mode if the device keeps bootlooping: https://topjohnwu.github.io/Magisk/faq.html)

**Comment by metaathron** [comment] 2023-02-16 06:39
Instaled apk, rebooted. So far so good. Installed magisk module, rebooted and bootlooped.

Funny thing, it bootloops even in safe mode. I had to remove magisk modules via adb `adb shell magisk --remove-modules` before unlocking the screen

**Comment by chenxiaolong** [comment] 2023-02-16 20:44
Darn.

Since adb is working before unlocking the screen, can you start `adb logcat > logcat.txt`, trigger the bootloop, and upload that file? I don't really have any idea of what might be wrong, but I can try taking a look at the logs to see if there's something obvious.

**Comment by metaathron** [comment] 2023-02-16 20:46
Sure, I can try that in the morning.

**Comment by metaathron** [comment] 2023-02-17 06:38
I have gone through the log myself a bit and I guess, it's linked with @Donaldcwl NFC issue.

**Comment by carstengrimm** [comment] 2023-02-17 17:32
Same Issue with my phone, but i am not having MIUI 14 but MIUI 13. 
Version 13.0.5.0 Xiaomi.eu Rom.

**Comment by yahorchik1** [comment] 2023-02-17 18:13
Have the same issue on Mi 11 Lite 5G NE after updating from EEA ROM 13.0.11.0 (MIUI13&A12) to V14.0.4.0 (MIUI14&A13).

**Comment by chenxiaolong** [comment] 2023-02-17 22:05
Thanks for the logs, @metaathron.

I think the root cause might be SELinux blocking Magisk from relabeling files:

```
02-17 07:30:03.124     1     1 W init    : type=1400 audit(0.0:476): avc: denied { relabelfrom } for name="com.chiller3.bcr" dev="dm-41" ino=370199 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir permissive=0
```

With BCR's module installed, would someone mind running the following in `adb shell` and post the output?

```
ls -lZd /system/priv-app/com.chiller3.bcr /system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml
su -c 'ls -lZ /data/adb/modules/'
```

The expected output is:
```
-rw-r--r-- 1 root root u:object_r:system_file:s0   292 2023-02-15 00:37 /system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml
drwxr-xr-x 2 root root u:object_r:system_file:s0  3452 2023-02-15 00:37 /system/priv-app/com.chiller3.bcr
<...>
drwxr-xr-x 3 root root u:object_r:system_file:s0  3452 2023-02-15 00:38 com.chiller3.bcr
```

Based on the logs, I suspect the files are labeled as `u:r:init:s0`. This is not just happening with BCR--for example, safetynet-fix is affected too:

```
02-17 07:30:03.120     1     1 W init    : type=1400 audit(0.0:465): avc: denied { relabelfrom } for name="safetynet-fix" dev="dm-41" ino=350231 scontext=u:r:init:s0 tcontext=u:object_r:system_file:s0 tclass=dir permissive=0
```

It's just that when Android's package manager (`installd`) can't access BCR's apk, both installd and nfc crash. Whereas when other module's files can't be accessed, nothing bad happens.

---

Also, can someone please post a direct link to where I can download one of the affected MIUI firmware? I'd like to take a look at the SELinux policy to see if this is something I can work around in BCR or if Magisk will need to be fixed.

**Comment by yahorchik1** [comment] 2023-02-18 07:38
@chenxiaolong Here you can download MIUI firmwares https://xiaomifirmwareupdater.com/miui/lisa/
You can select another model of phone.
I also use safetynet-fix module for magisk, it works perfect on MIUI14. Bootlop begins, when I enable BCR module in magisk. System reboots about in minute after booting. I have enough time to open magisk and disable BCR. Also, I can open BCR app.

**Comment by metaathron** [comment] 2023-02-18 08:11
Unfortunately, I won't have access to my computer for a few days, so I can't send you requested output now. Also, safetynet-fix didn't have any issue on my phone as well as lsposed.
My phone reboots just a few seconds after unlock, so I'm not even able to open magisk.

**Comment by carstengrimm** [comment] 2023-02-18 12:57
https://androidfilehost.com/?fid=4279422670115711159

That's my rom which I currently use.

**Comment by Donaldcwl** [comment] 2023-02-18 20:21
ROM Fastboot:
https://bigota.d.miui.com/V14.0.5.0.TLBMIXM/zeus_global_images_V14.0.5.0.TLBMIXM_20230110.0000.00_13.0_global_d1ba795dc9.tgz

**Comment by chenxiaolong** [comment] 2023-02-18 22:10
Thanks for all the info.

Based on the @Donaldcwl's output, my assumption in the previous post is wrong. Despite the selinux denials, the file labels are being set correctly, so that's not the root cause.

@metaathron mentioned that the same crashes occur with APH. Its Magisk module works exactly the same as BCR's--a new apk is added to `/system/priv-app` and a permissions file to `/system/etc/permissions`.

I don't know why MIUI doesn't like this method of adding new system apps. I don't see anything else that's problematic in the logcats that have been posted and I don't have any further ideas.

**Comment by yahorchik1** [comment] 2023-02-18 22:57
@chenxiaolong tried to install APH module, received the same bootlops as with BCR. But with my phone and firmware I have enough time before reboot to open magisk and disable module :)

**Comment by chenxiaolong** [comment] 2023-02-20 03:06
Please give this debug build a try:  [BCR-1.33.r8.g8b0add8-debug.zip](https://github.com/chenxiaolong/BCR/files/10779040/BCR-1.33.r8.g8b0add8-debug.zip)

It appears there is a known issue with Magisk's mounts when the ROM uses `overlayfs`. Looking at the ROMs posted above, MIUI does indeed to use `overlayfs` for several paths that BCR uses. I believe the problematic mount is:

```
overlay /system/etc/permissions overlay ro,lowerdir=/mnt/vendor/mi_ext/system/etc/permissions/:/product/pangu/system/etc/permissions/:/system/etc/permissions check,nofail
```

(This combines `/mnt/vendor/mi_ext/system/etc/permissions`, `/product/pangu/system/etc/permissions`, and `/system/etc/permissions` and makes all of their files visible at `/system/etc/permissions` at the same time.)

I'm guessing that after Magisk mounts BCR's files, the files originally from `/mnt/vendor/mi_ext/system/etc/permissions` and `/product/pangu/system/etc/permissions` are no longer visible in `/system/etc/permissions`. One of these files is `com.nxp.nfc.nq.xml`, so it makes sense that NFC breaks.

---

For those testing this new build, please upload these files:

* `adb pull /proc/self/mountinfo mountinfo.no_bcr` without BCR installed
* `adb pull /proc/self/mountinfo mountinfo.bcr` after BCR is installed
* The BCR installation logs (the icon in the top right corner in Magisk during module installation)

**Comment by carstengrimm** [comment] 2023-02-22 12:59
[mountinfo.bcr.txt](https://github.com/chenxiaolong/BCR/files/10803965/mountinfo.bcr.txt)
[mountinfo.no_bcr.txt](https://github.com/chenxiaolong/BCR/files/10803966/mountinfo.no_bcr.txt) 

```
- Copying zip to temp directory
- Installing BCR-1.33.r8.g8b0add8-debug.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/c.n.izitemxlhxzmo/cache/flash/install.zip
  inflating: module.prop
*****************
 BCR 
 by chenxiaolong 
*****************
Archive:  /data/user/0/c.n.izitemxlhxzmo/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/c.n.izitemxlhxzmo/cache/flash/install.zip
  inflating: module.prop
  inflating: customize.sh
  inflating: LICENSE
  inflating: README.md
   creating: overlay/
   creating: overlay/addon.d/
  inflating: overlay/addon.d/51-com.chiller3.bcr.sh
   creating: overlay/etc/
   creating: overlay/etc/permissions/
  inflating: overlay/etc/permissions/privapp-permissions-com.chiller3.bcr.xml
   creating: overlay/priv-app/
   creating: overlay/priv-app/com.chiller3.bcr/
  inflating: overlay/priv-app/com.chiller3.bcr/app-debug.apk
Using /system as the installation target
'/data/adb/modules_update/com.chiller3.bcr/overlay' -> '/data/adb/modules_update/com.chiller3.bcr/system'
- Done

```

no bootloop, 
com.chiller3bcr.recorderapplication no logo, instantly force close

**Comment by Art-y-7** [comment] 2023-02-22 16:19
Install BCR-1.33.r8.g8b0add8-debug.zip  -> Mi 11 lite 5G Ne
No no bootloop
call recording - OK

![Screenshot_2023-02-22-19-03-25-659_com topjohnwu magisk](https://user-images.githubusercontent.com/125752771/220688099-638b7b9c-90cc-400b-bba6-43f43e65edc6.jpg)
![Screenshot_2023-02-22-19-06-01-543_com chiller3 bcr](https://user-images.githubusercontent.com/125752771/220688114-7b04fee2-0304-4b14-9b8f-a214e3e807c6.jpg)

**Comment by chenxiaolong** [comment] 2023-02-22 20:03
Great! Since the bootloop is fixed/worked around, I will release a new version of BCR and close this issue.

@carstengrimm Can you grab a logcat with `adb logcat -d > logcat` right after BCR crashes and open a new issue?

@yahorchik1 Can you create a new issue for this and upload the log file that BCR created in the output directory for that call?

**Closed** 2023-02-22 20:06 UTC
