### ISSUE TITLE
No direction and sim slot in filename

### ISSUE THREAD

**Issue by illukin** [chenxiaolong/BCR#394] opened 2023-07-30 18:54 UTC
Hi!

I'm trying to use filename template like this: `{date:yyyy}/{phone_number:digits_only}/{date:yyyy-MM-dd_HH.mm.ss(XX)}[_{direction}|][_sim{sim_slot}|][_{phone_number:digits_only}|][_[{contact_name}|{caller_name}|{call_log_name}]|]`.
And there are no direction and sim slot in output filename. But in `*.json` file they are. Whats wrong?

Android 13
BCR v1.48
[log.txt](https://github.com/chenxiaolong/BCR/files/12209878/log.txt)

**Comment by chenxiaolong** [comment] 2023-07-30 21:12
Thanks for the logs. Could you also post one of the JSON files? (Feel free to replace sensitive information with placeholder text)

**Comment by chenxiaolong** [comment] 2023-07-31 01:59
I was able to reproduce the missing `direction` issue. That'll be resolved by #398.

For the SIM slot, do you only have one active SIM? If so, you'll need to use `{sim_slot:always}` because `{sim_slot}` only works when there are multiple SIMs active. This is a new feature added in #399.

**Closed** 2023-07-31 02:07 UTC
