### ISSUE TITLE
whatsapp call recording

### ISSUE THREAD

**Issue by cl84** [chenxiaolong/BCR#355] opened 2023-05-31 08:12 UTC
Is it possible to adapt this software to record whatsapp calls too? Thank you

**Comment by chenxiaolong** [comment] 2023-05-31 15:41
Nope, sorry. BCR is designed completely around Android's telephony framework, which is only used for phone calls. For recording calls in third-party apps, you'll have to use a different call recorder.

(Duplicate of #228, #235, #267, #340, #341)

**Closed as completed by chenxiaolong** 2023-05-31 15:41 UTC
Labels: duplicate, wontfix
