### ISSUE TITLE
[Request] Whatsapp call recording

### ISSUE THREAD

**Issue by Quidney** [chenxiaolong/BCR#267] opened 2023-03-16 14:18 UTC
Sorry if it's already a feature but I installed it on my rooted device using magisk and it doesn't seem to record whatsapp calls.

**Comment by chenxiaolong** [comment] 2023-03-16 19:52
Sorry, this is not something that will be implemented in BCR. BCR is heavily tied in with how cellular calls work on Android and cannot handle calls in third party apps. You'll have to use a different call recorder for that.

(Duplicate of #228, #235)

**Closed by chenxiaolong** 2023-03-16 19:52 UTC
