### ISSUE TITLE
VOIP call recordings

### ISSUE THREAD

**Issue by amandewett** [chenxiaolong/BCR#588] opened 2024-08-21 02:48 UTC
Is there any chance that we will get WhatsApp (VOIP) call recording feature?

**Comment by chenxiaolong** [comment] 2024-08-21 04:02
No, sorry. BCR is completely designed around Android's telephony framework, which only handles phone calls.

(Duplicate of #228, #235, #267, #340, #341, #355, #489, #490)

**Closed by chenxiaolong** 2024-08-21 04:02 UTC
Labels: duplicate, wontfix

**Comment by amandewett** [comment] 2024-08-21 11:19
> No, sorry. BCR is completely designed around Android's telephony framework, which only handles phone calls.
> 
> (Duplicate of #228, #235, #267, #340, #341, #355, #489, #490)

Ok, thank you :-(
