### ISSUE TITLE
Record WhatsApp calls.

### ISSUE THREAD

**Issue by oim37** [chenxiaolong/BCR#340] opened 2023-05-10 23:35 UTC
30% calls makes by WhatsApp, 10% Skype snd other 60% by mobile operator. Make record for whatsapp too.

**Comment by chenxiaolong** [comment] 2023-05-11 02:30
Sorry, this is not something that will be implemented in BCR. BCR is heavily tied in with how cellular calls work on Android and cannot handle calls in third party apps. You'll have to use a different call recorder for that.

(Duplicate of #228, #235, #267)

**Closed by chenxiaolong** 2023-05-11 02:30 UTC
