### ISSUE TITLE
App cashing

### ISSUE THREAD

**Issue by aka5hh** [chenxiaolong/BCR#545] opened 2024-05-18 15:03 UTC
The app is crashing on lastest kernelSU version 
![Screenshot_20240518-210320_Matrixx Home](https://github.com/chenxiaolong/BCR/assets/103891406/573508f9-4f87-46b2-bf6e-2618826f7af2)

**Comment by chenxiaolong** [comment] 2024-05-18 19:34
This is a duplicate of https://github.com/chenxiaolong/BCR/issues/486. Please see some of the suggestions from other folks there.

**Closed by chenxiaolong** 2024-05-18 19:34 UTC
Labels: duplicate, bug/limitation elsewhere
