### ISSUE TITLE
Can you add the function of recording calls to some Apps?

### ISSUE THREAD

**Issue by sunburst96** [chenxiaolong/BCR#235] opened 2023-02-09 20:08 UTC
For example, WeChat, this app is used more frequently than telephones in our country, and there are almost no suitable recording methods on the market. I would really appreciate it if you could join in 🙏🙏🙏

**Comment by chenxiaolong** [comment] 2023-02-09 21:00
Sorry,. I know it would be a useful feature, but this won't be implemented in BCR. BCR's call detection and recording mechanism is based on Android's telephony framework, which isn't used by apps like WeChat and WhatsApp.

(Duplicate of #228)

**Closed** 2023-02-09 21:00 UTC
Labels: wontfix
