### ISSUE TITLE
Failed to record call

### ISSUE THREAD

**Issue by crazyuploader** [chenxiaolong/BCR#207] opened 2022-12-27 08:45 UTC
Getting an issue where calls are not saved by a particular caller whose name has characters like "$", "¥".

Caller name example: `$string¥`

![Screenshot_20221224-212606_GPay](https://user-images.githubusercontent.com/49350241/209635467-21de3860-4a7d-4635-8c4b-b83d29361f9b.png)

**Comment by chenxiaolong** [comment] 2022-12-27 21:02
Interesting. I'm curious where that comes from because BCR does not try to process the caller name in any way. I'll see if I can reproduce the issue with `$string¥`.

Are you able to receive another call from this caller easily? If so, can you enable debug mode by long pressing the version number and then try the call? BCR will create a log file inside the output directory.

**Comment by chenxiaolong** [comment] 2022-12-27 21:23
This should be fixed by #209, which will be included in the next version (1.28).

**Closed** 2022-12-27 21:23 UTC
Labels: bug
