### ISSUE TITLE
BCR CRASHING

### ISSUE THREAD

**Issue by sandirickyroy** [chenxiaolong/BCR#553] opened 2024-05-31 06:12 UTC
BCR keeps crashing everytime time I connect a phone call.

[ERROR_crash.log (32).txt](https://github.com/user-attachments/files/15509072/ERROR_crash.log.32.txt)

**Comment by chenxiaolong** [comment] 2024-05-31 14:42
Duplicate of #544.

**Closed by chenxiaolong** 2024-05-31 14:42 UTC
Labels: bug/limitation elsewhere
